name: MoModeratorPlus
version: '1.0.3-BETA'
main: top.molab.minecraft.moModeratorPlus.MoModeratorPlus
api-version: '1.20'
load: POSTWORLD
softdepend: [ "PlaceholderAPI" ]
commands:
  MoModeratorPlus:
    description: MoModeratorPlus Commands
    usage: /MoModeratorPlus
    permission: moModPlus.admin
    aliases:
      - MoModPlus
      - mmp
      - mm+
  ban:
    description: MoModeratorPlus Ban
    usage: /ban
    permission: moModPlus.admin.ban
    aliases: [ ]

  banip:
    description: MoModeratorPlus BanIP
    usage: /banip
    permission: moModPlus.admin.banip
    aliases:
      - ban-ip
  mute:
    description: MoModeratorPlus Mute
    usage: /mute
    permission: moModPlus.admin.mute
    aliases: [ ]

  kick:
    description: MoModeratorPlus Kick
    usage: /kick
    permission: moModPlus.admin.kick
    aliases: [ ]

  unban:
    description: MoModeratorPlus Unban
    usage: /unban
    permission: moModPlus.admin.unban
    aliases: [ ]

